apiVersion: v1
kind: Service
metadata:
  name: counting-service
  labels:
    app: counting-service-app
    version: v1
spec:
  selector:
    app: counting-service-app
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 9001
  type: NodePort